### ISSUE TITLE
metal line list

### ISSUE THREAD

**Issue by HajimeKawahara** [HajimeKawahara/exojax#17]

**Comment by HajimeKawahara** [comment]
toward main-sequence stars

**Comment by chonma0ctopus** [comment]
I've made the VALD3 atomic data available. The usage example is shown [here](https://github.com/chonma0ctopus/exojax/blob/metalline/examples/tutorial/Foward%20modeling%20for%20metal%20line.ipynb).
Note that I assume all elements (as line absorption source) exist in a neutral state when the MMR is calculated in the above example.

**Comment by HajimeKawahara** [comment]
@chonma0ctopus Thank you! Can you send a PR?

**Comment by chonma0ctopus** [comment]
I compared the Fe I opacity with that of petitRADTRANS [here](https://github.com/chonma0ctopus/exojax/blob/metalline/examples/comparisons/compare_atomic_opacity_with_petitRADTRANS.ipynb).
The lower side does not match, but it looks good for the prominent absorption lines.

The difference of the lower side could be due to the treatment of the damping wing...? Let me continue a little further investigation.

**Comment by HajimeKawahara** [comment]
See PR #171.
