### ISSUE TITLE
Rechecks CIA  

### ISSUE THREAD

**Issue by HajimeKawahara** [HajimeKawahara/exojax#433]
The CIA is now important for the real retrieval problem. So, we'd like to recheck the CIA. 
This issue is a part of the #427 code comprehensive review

Related: 
The current implementation of the CIA was partly validated by [comparing with pRT](https://github.com/HajimeKawahara/exojax/issues/5#issuecomment-820883108)

**Comment by ykawashima** [comment]
I realized that the difference of the previous comparison with [petitRADTRANS](https://github.com/HajimeKawahara/exojax/issues/5#issuecomment-820883108) also seems to be a few % (due to the inclusion of molecular absorption, the difference looks smaller), which is similar to the one found in the [current comparison](https://github.com/HajimeKawahara/exojax/issues/427#issuecomment-1890468045).

**Comment by HajimeKawahara** [comment]
Thank you! I agree.
