### ISSUE TITLE
Confirmation of H- opacity

### ISSUE THREAD

**Issue by HajimeKawahara** [HajimeKawahara/exojax#94]
We haven't compared the hminus opacity merged in the develop branch  to other codes yet.
See #90 for more details.

**Comment by HajimeKawahara** [comment]
@bmorris3 @daniel-kitzmann
I merged the h-minus branch to the develop one because @daniel-kitzmann kindly checked the implementation while I have still difficulty to compare the results with petitRadtrans. I hope we will come up with a good way to check as we use this new functionality.

Here is a short summary so far:
- The hminus code of @daniel-kitzmann computes H- using the Saha equation with given e- and H abundance.
- In petitRadtrans, it looks we need to specify H- abundance directly (abundances['H-']), but even this looks not to affect the results.  
- So currently we have no way to compare with each others.

**Comment by astrostevanus** [comment]
I can confirm that the log_hminus_continuum script is perfectly match with John et al. 1988 except, of course, the alpha value in the paper which should have been 1.439x10^4 if wavelength input is in micron. Although I haven't been able to validate the dtauhminus.

**Comment by astrostevanus** [comment]
Hi Kawahara-san, I have overlooked line 26 in hminus.py, the wavenumber should not be reversed, it should be     "wavelength_um=1e4/nus". Otherwise the H- opacity will be reversed. I have compared it with petitRadTrans and the "kink" should be at around 1.6 micron. There is still a mismatch in the strength of H- opacity between Exojax and petitRadTrans which I haven't figured out the cause. I should note though that petitRadTrans adopt the H- opacity equation from David F. Gray's textbook ("The Observation and Analysis of Stellar Photospheres") page 156.
![OH_with_Hminus_b4_corr](https://user-images.githubusercontent.com/52459733/153203496-b72bd068-8d97-418c-af7a-8164dc5f009b.png)
![OH_with_Hminus_after_corr](https://user-images.githubusercontent.com/52459733/153203522-41c05efc-2b37-4954-8c04-8bf4c9a5185c.png)

**Comment by HajimeKawahara** [comment]
@astrostevanus Thanks for the report! Can you send a PR for this bug?

**Comment by astrostevanus** [comment]
Sure, I will make one shortly!

**Comment by astrostevanus** [comment]
Oh yeah, sorry, I must have made a mistake.

**Comment by HajimeKawahara** [comment]
I think before the PR you can update your branch by
`git pull origin develop`

**Comment by HajimeKawahara** [comment]
@astrostevanus 
oh, sorry you directly push the bug fix in `develop` branch.

**Comment by HajimeKawahara** [comment]
Then, it's okay, you do not need to send a new PR. Thanks. @astrostevanus 
but usually we make a new branch, for instance, `feature/xxx` from `develop` branch, and send a PR `feature/xxx` to `develop`.
if you feel you do not review, i.e. refactoring and so on, you can merge by yourself. otherwise, specify the reviewer(s).

**Comment by astrostevanus** [comment]
Understood! I'll do that next time. Thanks!

**Comment by astrostevanus** [comment]
Hi Kawahara-san, I found a bug in my code that calculate the dlogP without the log. Please find attached the OH emission spectrum models that I created using petitRadtrans, Exojax-MODIT but with OH cross-section calculated using HELIOS-K, and Exojax-MODIT using HELIOS-K-based binary linelists. The continuum level and the line strengths are almost similar to the one from petitRadtrans. I think the difference is mainly coming from the adoption of different equation to calculate the H- cross-section like Daniel said in #90.

![OH_comparison](https://user-images.githubusercontent.com/52459733/153356697-002052dc-6bff-4d35-8b08-eb0297aab357.png)

![Opacity_comparison](https://user-images.githubusercontent.com/52459733/153356708-b4c0ab32-c405-414b-a55b-33b4ecc2074d.png)

**Comment by HajimeKawahara** [comment]
@astrostevanus Thanks, great!
